pipeline {
    agent {
        docker{
        image 'node:16.13.1-alpine'
        args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        npm_config_cache = 'npm-cache'
    }
    stages {
        stage('Build'){
            steps{
                sh 'yarn install'
                sh "chmod +x -R ${env.WORKSPACE}"
                sh 'yarn build'
            }
        }
        stage('Deliver') {
           agent none
            steps {
                    sh 'ls /var/lib/jenkins/workspace/'
            }
        }
    }
}